# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f178712503cb314c0b54fafe907f66041fe3e6d41e82ff7910f2ff3c0a6d3204d51948f2dcf41316efb742d7c134ce150aa3f427f5cbc69e5bca5107f40c191

test:
  secret_key_base: 8eb11e97f2cbdb2f7154e960598bc596040d92c1b23af3fe0c6f9dff3763fdcb7ee659eb3da2b0274e8bd32a66c431888161b40e2b409d8c880d575e06706580

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
